sonar.verbose=true
sonar.organization=hamzafijahi2001
sonar.projectKey=hamzafijahi2001-key_client-flow
sonar.projectName=client-flow
sonar.projectVersion=1.0
sonar.sources=backend,frontend
sonar.tests=backend/app/tests,frontend/src
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/node_modules/**
sonar.test.inclusions=**/tests.py,**/*.test.jsx
sonar.coverage.exclusions=**/migrations/**,**/node_modules/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=**/migrations/**,**/node_modules/**
