# Generated by Django 6.0.4 on 2026-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(1, 'lead'), (2, 'active'), (3, 'archived')], default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'planning'), (2, 'active'), (3, 'done')], default=2),
        ),
    ]
