# Generated by Django 6.0.4 on 2026-05-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_client_status_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('priority', models.IntegerField(choices=[(1, 'Must Have'), (2, 'Should Have'), (3, 'Could Have'), (4, "Won't Have")], default=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.project')),
            ],
        ),
    ]
